# markdownlint-cli2 configuration
# See https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

# Glob patterns for files to lint
globs:
  - "**/*.md"

# Glob patterns for files to ignore
ignores:
  - "node_modules"
  - ".gradle"
  - "build"

# markdownlint rules configuration
config:
  # MD013/line-length - Line length
  MD013:
    line_length: 120
    code_blocks: false
    tables: false

  # MD033/no-inline-html - Inline HTML
  MD033: false

  # MD041/first-line-heading - First line in file should be a top level heading
  MD041: false
